# Generated by Django 3.2.12 on 2022-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_listingowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.FloatField(blank=True),
        ),
    ]
