# Generated by Django 3.2.12 on 2022-05-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220509_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='currentBid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(default=models.FloatField(blank=True, default=0.0), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.bid'),
        ),
    ]
