# Generated by Django 3.2.12 on 2022-05-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20220509_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
