# Generated by Django 3.2.12 on 2022-05-12 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_listingowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='userList', to=settings.AUTH_USER_MODEL),
        ),
    ]
